services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    container_name: api
    ports:
      - "8082:8080"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/todo"

    depends_on:
        db:
          condition: service_healthy
    command: ["sh", "-c", "npx prisma generate && ts-node prisma/seed.ts && node dist/server.js"]
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env

  web:
    build: ./frontend
    container_name: web
    volumes:
      - ./frontend:/app
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: "http://localhost:8082"
    depends_on:
      - api

volumes:
  db_data:
